name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
          INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          timeout: 300s
          command_timeout: 600s
          envs: INFISICAL_CLIENT_ID,INFISICAL_CLIENT_SECRET
          script: |
            set -e

            if ! command -v infisical >/dev/null 2>&1; then
              curl -1sLf 'https://artifacts-cli.infisical.com/setup.deb.sh' | sudo -E bash
              sudo apt-get update
              sudo apt-get install -y infisical
            fi

            cd /srv/post_generator/post_generator_deploy_conf || exit 1

            export INFISICAL_TOKEN=$(infisical login --method=universal-auth --client-id="$INFISICAL_CLIENT_ID" --client-secret="$INFISICAL_CLIENT_SECRET" --domain=https://eu.infisical.com --silent --plain)
            if [ -z "$INFISICAL_TOKEN" ]; then
              echo "Infisical login failed or returned empty token"
              exit 2
            fi

            git pull origin main

            infisical run --env=prod --domain=https://eu.infisical.com -- docker compose up -d --build

            echo "Deployment completed successfully!"
