name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          timeout: 300s
          command_timeout: 1800s
          script: |
            set -e
            cd /srv/post_generator/post_generator_deploy_conf
            INFISICAL_OUTPUT=$(infisical login --method=universal-auth \
              --client-id=${{ secrets.INFISICAL_CLIENT_ID }} \
              --client-secret=${{ secrets.INFISICAL_CLIENT_SECRET }} \
              --silent --plain \
              --domain https://eu.infisical.com 2>&1) || true
            if echo "$INFISICAL_OUTPUT" | grep -iq "error\|access denied\|usage limit"; then
              echo "WARNING: Infisical login failed:"
              echo "$INFISICAL_OUTPUT"
            else
              INFISICAL_TOKEN=$(echo "$INFISICAL_OUTPUT" | tr -d '\r\n')
              if [ -n "$INFISICAL_TOKEN" ]; then
                export INFISICAL_TOKEN
                echo "Infisical token exported"
              else
                echo "Infisical login returned empty token; continuing without exported token"
              fi
            fi
            git pull origin main
            docker compose pull || true
            docker compose up -d --build
            docker compose ps
            echo "Deployment completed successfully!"
