name: Deploy to VPS

# Триггеры для запуска workflow
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Позволяет запускать вручную из GitHub UI

jobs:
  deploy:
    name: Deploy to VPS Server
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22 # Стандартный SSH порт (можно изменить если нужно)
          timeout: 300s # Таймаут подключения
          command_timeout: 600s # Таймаут выполнения команд
          script: |
            # Переходим в директорию проекта (ЗАМЕНИТЕ НА СВОЙ ПУТЬ)
            cd /srv/post_generator/post_generator_deploy_conf
            
            # Обновляем репозиторий
            echo "Updating repository..."
            git pull origin main
            
            # Запускаем Makefile для сборки и запуска контейнеров
            echo "Starting containers..."
            make
            
            echo "Deployment completed successfully!"