name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          timeout: 300s
          command_timeout: 600s
          script: |
            cd /srv/post_generator/post_generator_deploy_conf

            # Обновление Infisical (опционально)
            # sudo apt-get update && sudo apt-get install infisical

            # Установка региона через переменную окружения
            export INFISICAL_URL=https://eu.infisical.com

            echo "Authenticating with Infisical..."
            # Аутентификация без указания domain в параметрах
            infisical login --method=universal-auth \
              --client-id=${{ secrets.INFISICAL_CLIENT_ID }} \
              --client-secret=${{ secrets.INFISICAL_CLIENT_SECRET }}

            echo "Updating repository..."
            git pull origin main

            echo "Starting containers..."
            # Используем переменную окружения для домена
            infisical run --env=prod -- docker compose up -d --build

            echo "Deployment completed successfully!"